import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // OpenNext/Cloudflare build outputs (huge bundled JS — linting them hangs eslint):
    ".open-next/**",
    ".wrangler/**",
    // generated by `pnpm cf-typegen`
    "cloudflare-env.d.ts",
  ]),
]);

export default eslintConfig;
