// GENERATED by scratchpad/gen_redirects.py from docs/seo/{her-legacy-posts.json,extra-redirects.txt}.
// Do NOT hand-edit — re-run the generator. Legacy permalinks -> new URLs (HTTP 301).
export type LegacyRedirect = { source: string; destination: string };
export const LEGACY_REDIRECTS: LegacyRedirect[] = [
  { source: "/2024/10/11/navigating-gender-identity-and-self-expression-a-journey-beyond-societal-norms", destination: "/blog/navigating-gender-identity-and-self-expression-a-journey-beyond-societal-norms" },
  { source: "/2024/10/11/exploring-the-interplay-of-cultural-identity-and-personal-growth-a-journey-of-self-discovery-and-development", destination: "/blog/exploring-the-interplay-of-cultural-identity-and-personal-growth-a-journey-of-self-discovery-and-development" },
  { source: "/2024/10/11/the-intricacies-of-self-identity-unraveling-the-psychological-underpinnings", destination: "/blog/the-intricacies-of-self-identity-unraveling-the-psychological-underpinnings" },
  { source: "/2024/10/11/canvas-of-the-soul-the-intersection-of-art-and-self-expression", destination: "/blog/canvas-of-the-soul-the-intersection-of-art-and-self-expression" },
  { source: "/2024/10/11/philadelphias-chinatown-a-vibrant-haven-for-chinese-immigrants", destination: "/blog/philadelphias-chinatown-a-vibrant-haven-for-chinese-immigrants" },
  { source: "/2024/10/11/riding-through-time-the-past-present-and-future-of-public-transportation-in-philadelphia", destination: "/blog/riding-through-time-the-past-present-and-future-of-public-transportation-in-philadelphia" },
  { source: "/2024/10/11/the-ripple-effects-of-remigration-unraveling-its-impact-on-family-bonds", destination: "/blog/the-ripple-effects-of-remigration-unraveling-its-impact-on-family-bonds" },
  { source: "/2024/10/11/navigating-the-silence-understanding-the-impact-of-language-barriers-on-mental-health", destination: "/blog/navigating-the-silence-understanding-the-impact-of-language-barriers-on-mental-health" },
  { source: "/2026/03/03/navigating-the-fear-of-deportation-coping-skills-to-reduce-anxiety", destination: "/blog/navigating-the-fear-of-deportation-coping-skills-to-reduce-anxiety" },
  { source: "/2026/03/06/grief-that-comes-in-waves-why-it-returns-and-how-to-cope-with-compassion", destination: "/blog/grief-that-comes-in-waves-why-it-returns-and-how-to-cope-with-compassion" },
  { source: "/2026/03/06/when-the-night-doesnt-feel-safe-trauma-hypervigilance-and-difficulty-sleeping", destination: "/blog/when-the-night-doesnt-feel-safe-trauma-hypervigilance-and-difficulty-sleeping" },
  { source: "/2026/03/06/the-quiet-weight-of-imposter-syndrome-why-you-feel-like-you-dont-belong-and-how-to-cope", destination: "/blog/the-quiet-weight-of-imposter-syndrome-why-you-feel-like-you-dont-belong-and-how-to-cope" },
  { source: "/2026/03/06/https-growthjourneytherapy-com-2026-03-06-sourcing-calm-from-the-outdoors-how-nature-helps-regulate-a-stressed-nervous-system", destination: "/blog/sourcing-calm-from-the-outdoors-how-nature-helps-regulate-a-stressed-nervous-system" },
  { source: "/2026/03/06/sourcing-calm-from-the-outdoors-how-nature-helps-regulate-a-stressed-nervous-system", destination: "/blog/sourcing-calm-from-the-outdoors-how-nature-helps-regulate-a-stressed-nervous-system" },
  { source: "/2026/03/12/why-am-i-lonely-even-though-i-have-friends", destination: "/blog/why-am-i-lonely-even-though-i-have-friends" },
  { source: "/2026/03/12/family-separation-and-deportation-stress-coping-tools-for-undocumented-families", destination: "/blog/family-separation-and-deportation-stress-coping-tools-for-undocumented-families" },
  { source: "/2026/03/12/high-functioning-but-exhausted-when-you-look-fine-but-feel-overwhelmed", destination: "/blog/high-functioning-but-exhausted-when-you-look-fine-but-feel-overwhelmed" },
  { source: "/2026/04/01/high-functioning-burnout-when-youre-getting-everything-done-but-still-exhausted", destination: "/blog/high-functioning-burnout-when-youre-getting-everything-done-but-still-exhausted" },
  { source: "/2026/04/10/stuck-in-a-procrastination-loop-how-to-take-action-without-motivation", destination: "/blog/stuck-in-a-procrastination-loop-how-to-take-action-without-motivation" },
  { source: "/2023/05/02/que-es-la-deprivacion-cultural-2", destination: "/blog/que-es-la-deprivacion-cultural" },
  { source: "/specialties/burn-out-work-life-balance-2", destination: "/specialties/burn-out-work-life-balance" },
];
